server:
  port: 8084   #port for the orderservice

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BattulaLikhit/CentralizedConfig  # Replace with your actual repo
          clone-on-start: true
          skip-ssl-validation: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
 endpoint:
   health:
    show-details: always

