spring:
  application:
    name: quizservice

  datasource:
    url: jdbc:mysql://localhost:3306/quizdb?createDatabaseIfNotExist=true
    username: root
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Fixed indentation here
    show-sql: true  # Fixed indentation here

server:
  port: 2004
#spring.mvc.view.prefix=/WEB-INF/view/
#spring.mvc.view.suffix=.jsp


#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update



